class castingCost: 
   cost = { \
      'images/mtg/creatures/alGore.jpg':'green', \
      'images/mtg/creatures/americanEagle.jpg':'whitebluered', \
      'images/mtg/creatures/annoyingOrange.jpg':'whiteblackgreenbluered', \
      'images/mtg/creatures/arbalestElite.jfif':'white', \
      'images/mtg/creatures/arrgh.jpg':'black', \
      'images/mtg/creatures/averageAmerican.jpg':'red', \
      'images/mtg/creatures/barackHObama.jpg':'red', \
      'images/mtg/creatures/barackObama.jpg':'whitegreenblue', \
      'images/mtg/creatures/barackObamaII.jpg':'green', \
      'images/mtg/creatures/batman.jpg':'whiteblue', \
      'images/mtg/creatures/batmanII.jpg':'whiteblack', \
      'images/mtg/creatures/berneyStinson.jpg':'red', \
      'images/mtg/creatures/bernieSanders.jpg':'white', \
      'images/mtg/creatures/bernieSandersII.jpg':'whiteblackgreenbluered', \
      'images/mtg/creatures/bickeringGiant.jpg':'blackgreenred', \
      'images/mtg/creatures/blackKnight.jpg':'black', \
      'images/mtg/creatures/bruceLee.jpg':'whiteblackgreenbluered', \
      'images/mtg/creatures/burninator.jpg':'red', \
      'images/mtg/creatures/cantinaBand.jpg':'white', \
      'images/mtg/creatures/captainSisay.jpg':'whitegreen', \
      'images/mtg/creatures/charlesXavier.jpg':'whiteblue', \
      'images/mtg/creatures/cheatyFace.jpg':'blue', \
      'images/mtg/creatures/chivalrousChevalier.jpg':'white', \
      'images/mtg/creatures/chuckNorris.jpg':'green', \
      'images/mtg/creatures/daenerysStormborn.jpg':'whiteblackgreenred', \
      'images/mtg/creatures/daringSaboteur.jpg':'blue', \
      'images/mtg/creatures/darthSidious.jpg':'blackbluered', \
      'images/mtg/creatures/darthVader.jpg':'black', \
      'images/mtg/creatures/deadPool.png':'blackred', \
      'images/mtg/creatures/deadPoolAgain.jpg':'blackred', \
      'images/mtg/creatures/deadpoolFairyPrincess.jpg':'blackred', \
      'images/mtg/creatures/deadPoolIII.png':'blackred', \
      'images/mtg/creatures/doge.jpg':'white', \
      'images/mtg/creatures/drHouse.jpg':'white', \
      'images/mtg/creatures/drStrange.jpg':'whiteblackblue', \
      'images/mtg/creatures/earlOfSquirrel.jpg':'green', \
      'images/mtg/creatures/extremelySlowZombie.jpg':'black', \
      'images/mtg/creatures/gameStoreEmployee.jpg':'blue', \
      'images/mtg/creatures/generalGrievous.jpg':'whiteblackblue', \
      'images/mtg/creatures/georgeBushII.jpg':'whitebluered', \
      'images/mtg/creatures/georgeWBush.jpg':'red', \
      'images/mtg/creatures/god.png':'whiteblackgreenbluered', \
      'images/mtg/creatures/gordonRamsey.jpg':'red', \
      'images/mtg/creatures/groundPounder.jpg':'green', \
      'images/mtg/creatures/hangman.jpg':'black', \
      'images/mtg/creatures/hanSolo.jpg':'white', \
      'images/mtg/creatures/hillaryClinton.jpeg':'whitered', \
      'images/mtg/creatures/ifThatGetsLeftHanging.jpg':'red', \
      'images/mtg/creatures/infinityElemental.jpg':'red', \
      'images/mtg/creatures/ironMan.png':'whitered', \
      'images/mtg/creatures/ironManII.jpg':'whitered', \
      'images/mtg/creatures/jaceTheAsshole.jpg':'blue', \
      'images/mtg/creatures/jangoFett.jpg':'red', \
      'images/mtg/creatures/jeanGrey.jpg':'blackred', \
      'images/mtg/creatures/johnLennon.jpg':'greenblue', \
      'images/mtg/creatures/johnnyCash.jpg':'whiteblack', \
      'images/mtg/creatures/johnnyCombo.png':'blue', \
      'images/mtg/creatures/joshLane.jpg':'whiteblackgreenbluered', \
      'images/mtg/creatures/kanyeWest.png':'black', \
      'images/mtg/creatures/killerBunny.jpg':'white', \
      'images/mtg/creatures/kittyPryde.jpg':'whiteblue', \
      'images/mtg/creatures/koolAidMan.jpg':'red', \
      'images/mtg/creatures/krillin.jpg':'white', \
      'images/mtg/creatures/logan.jpg':'greenred', \
      'images/mtg/creatures/lordVoldemort.jpg':'black', \
      'images/mtg/creatures/magneto.jpg':'blackbluered', \
      'images/mtg/creatures/mario.jpg':'red', \
      'images/mtg/creatures/masterfulNinja.jpg':'black', \
      'images/mtg/creatures/memePirate.jpeg':'bluered', \
      'images/mtg/creatures/mrT.jpg':'whitered', \
      'images/mtg/creatures/mrTII.jpg':'whiteblackgreenbluered', \
      'images/mtg/creatures/mtgPlayer.png':'white', \
      'images/mtg/creatures/mystique.jpg':'blackblue', \
      'images/mtg/creatures/mythBusters.jpg':'red', \
      'images/mtg/creatures/nerdyPlayer.jpeg':'black', \
      'images/mtg/creatures/noviceBountyHunter.jpg':'red', \
      'images/mtg/creatures/obiWanKenobi.jpg':'whitegreenblue', \
      'images/mtg/creatures/oliviaVampire.jpg':'blackred', \
      'images/mtg/creatures/painiac.jpg':'red', \
      'images/mtg/creatures/partycrasher.jpg':'red', \
      'images/mtg/creatures/peasants.png':'whitegreen', \
      'images/mtg/creatures/pepe.jpg':'black', \
      'images/mtg/creatures/phoebeHeadOfSneak.jpg':'blackblue', \
      'images/mtg/creatures/princessLeia.jpg':'whitegreenblue', \
      'images/mtg/creatures/ragePlayer.jpeg':'red', \
      'images/mtg/creatures/ralphNader.jpg':'blackgreen', \
      'images/mtg/creatures/redForman.jpg':'red', \
      'images/mtg/creatures/riddick.jfif':'blackred', \
      'images/mtg/creatures/rocketTropper.jpg':'red', \
      'images/mtg/creatures/samuelJackson.jpg':'whiteblackgreenbluered', \
      'images/mtg/creatures/santaClaus.jpg':'green', \
      'images/mtg/creatures/scorpionKing.jpg':'blackred', \
      'images/mtg/creatures/secretGamer.jpeg':'white', \
      'images/mtg/creatures/sirBedevere.jpg':'whiteblue', \
      'images/mtg/creatures/sirRobin.png':'whiteblue', \
      'images/mtg/creatures/skinShifter.jpg':'green', \
      'images/mtg/creatures/skullSaucer.jpg':'black', \
      'images/mtg/creatures/sneakDispatcher.png':'blue', \
      'images/mtg/creatures/spiderman.jpg':'bluered', \
      'images/mtg/creatures/spidermanII.png':'bluered', \
      'images/mtg/creatures/spyEye.png':'blue', \
      'images/mtg/creatures/stoneColdBasilisk.jpg':'green', \
      'images/mtg/creatures/superBattleDroid.jpg':'blue', \
      'images/mtg/creatures/superman.gif':'blue', \
      'images/mtg/creatures/supermanII.jpg':'white', \
      'images/mtg/creatures/supermanIII.png':'whitebluered', \
      'images/mtg/creatures/surgeonCommander.png':'green', \
      'images/mtg/creatures/theCollector.jpeg':'green', \
      'images/mtg/creatures/theJoker.jpg':'blackred', \
      'images/mtg/creatures/theSilence.jpg':'black', \
      'images/mtg/creatures/timmyPowerGamer.jpg':'green', \
      'images/mtg/creatures/toughNerd.jpeg':'red', \
      'images/mtg/creatures/tournamentGrinder.jpg':'black', \
      'images/mtg/creatures/trooperCommander.jpg':'green', \
      'images/mtg/creatures/trump.jpg':'whitebluered', \
      'images/mtg/creatures/wallOfTrump.png':'whiteblue', \
      'images/mtg/creatures/weepingStatue.jpg':'white', \
      'images/mtg/creatures/wharfinfiltrator.jpg':'blue', \
      'images/mtg/creatures/youngChild.jpeg':'white', \
   }
   def __init__(self):
      pass
